### ISSUE TITLE
three related projects

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#101]
https://openstreetmap.be/en/projects.html has https://openstreetmap.be/en/projects/howto.html
These pages should probably not be top level projects?:
https://openstreetmap.be/en/projects/howto/leaflet.html
https://openstreetmap.be/en/projects/howto/openlayers.html

**Comment by jbelien** [comment]
Yeah, I noticed that a few days ago.

Since, it's "sub-pages", the 2 following pages should not appear on the main project page:
- https://openstreetmap.be/en/projects/howto/leaflet.html
- https://openstreetmap.be/en/projects/howto/openlayers.html

Thanks for the reminder!
