### ISSUE TITLE
Subscribing to the newsletter is hard

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/website#163]
The link to the newsletter is pretty hidden on the website. It deserves a more prominent place, e.g. in the 'contact'-section and/or the footer.

**Comment by joostschouppe** [comment]
Added to the community index, so shows up now

Suggest we add to the footer of the page, below the OKBE logo:

[Subscribe](https://members.osm.be/subscribe/newsletter) to our quarterly newsletter ([archive](https://us13.campaign-archive.com/home/?u=cc6632a49e784f67574e50269&id=5c2416bba6))
[Schrijf je in](https://members.osm.be/subscribe/newsletter
) voor onze driemaandelijkse nieuwsbrief ([archief](https://us13.campaign-archive.com/home/?u=cc6632a49e784f67574e50269&id=5c2416bba6))
same in french :)

**Comment by joostschouppe** [comment]
Upon closer inspection, it probably make sense to add the Newsletter to the ... News section :)
I mean include the text above also in the right column at https://openstreetmap.be/en/news.html
