### ISSUE TITLE
language switch should go to the same page

### ISSUE THREAD

**Issue by MarcBessieres** [osmbe/website#17]
currently it goes to the main page of the new language

**Comment by MarcBessieres** [comment]
For me it doesn't work, it seems that "website" is missing in the URL, but maybe this is an artefact of github.io

for example on:
https://osmbe.github.io/website/2016/10/14/nl-motm-sus-vhv.html
clicking on fr points to:
https://osmbe.github.io/2016/10/14/fr-motm-sus-vhv.html
instead of
https://osmbe.github.io/website/2016/10/14/fr-motm-sus-vhv.html

See the missing website before the date
But is is much better than yesterday!!!

**Comment by jbelien** [comment]
Sorry for he mess in the commits >_<

**Comment by xivk** [comment]
- [ ] We need to revert the 'website' path once the site is on the osm.be domain.

**Comment by jbelien** [comment]
Indeed :)
