### ISSUE TITLE
finish the formatting of the blog entries

### ISSUE THREAD

**Issue by MarcBessieres** [osmbe/website#18]
currently most of the blog entries only have just been imported without any formatting

**Comment by xivk** [comment]
The blogposts translate as long as they have the same file name except for the language tag. So we need to check for each post:

- [ ] Do the posts in different languages have the same filename.

**Comment by xivk** [comment]
Posts todo:

- [ ] osm-be open
- [ ] okfn
- [ ] ben laenen
- [ ] 2014-11-23-nl-missing-maps-mapathon
- [ ] 2014-11-23-nl-missing-maps-mapathon
- [ ] 2014-12-01-en-motm-guy-vanvuchelen
- [ ] 2015-01-01-en-motm-guy-roman
- [ ] 2015-03-02-en-motm-brecht-bonne
- [ ] 2015-03-20-en-motm-pierre-parmentier
- [ ] 2015-03-31-en-motm-josefien-and-ruben
- [ ] 2015-05-05-en-motm-brice-maron
- [ ] 2015-06-02-fr-motm-joost-schouppe
- [ ] 2015-07-16-fr-motm-marc-gemis
- [ ] 2015-08-01-en-mapper-of-the-month
- [ ] 2015-08-22-fr-motm-matthieu-gaillet
- [ ] 2015-09-03-en-mapper-of-the-month
- [ ] 2015-09-30-fr-motm-vincent-van-eyke
- [ ] 2015-10-29-en-mapper-of-the-month
- [ ] 2015-10-31-fr-motm-olivier-roussel
- [ ] 2015-12-11-nl-missing-maps-msf-handicap-international
- [ ] 2015-12-30-nl-motm-polyglot
- [ ] 2016-02-02-en-motm-ponci4520
- [ ] 2016-03-12-en-motm-nick
- [ ] 2016-04-22-en-motm-stijn-rombauts
- [ ] 2016-05-15-en-motm-pete-masters
- [ ] 2016-06-19-en-motm-julien-fastre
- [ ] 2016-08-20-en-motm-jorieke-vyncke
- [ ] 2016-09-04-fr-national-mapathon-swaziland
- [ ] 2016-09-21-en-september-is-maptember
- [ ] 2016-10-05-fr-missing-maps-msf-handicap-international
- [ ] 2016-10-14-en-motm-sus-vhv
- [ ] 2016-10-31-en-motm-clifford-snow

**Comment by MarcBessieres** [comment]
doing them also in parallel

**Comment by MarcBessieres** [comment]
I reviewed them, I think :)
but there have been problems for a few days in the generation of the web page. I don't know how to find the error, may be some help is available or I can check next week.

By the way, there is no uniformity in the way the questions are highlighted, nor how is the formatting of the first paragraph( often italic but not always). Shall we make it all the same?

**Comment by Jorieke** [comment]
I think @xivk solved the issue with the generation of the web page. Apparently I did something wrong somewhere ;-)  

On the formatting, yes let's try to do it all the same. I propose: 
- first paragraph in Italic
- questions and onther interviewer remarks in bolt; so with the two little stars before and after the question

**Comment by Jorieke** [comment]
Damn I closed the issue, that was not what I wanted :-p

**Comment by jbelien** [comment]
@MarcBessieres @Jorieke 

May I close this issue ? Could you confirm that the work is done ?

Thanks :)
