### ISSUE TITLE
Include Meetup calender

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#2]
Maybe with: http://embed.ly/provider/meetup

**Comment by xivk** [comment]
Leaving this issue open, but suggested for now to:

- [ ] Add a social media widget, including twitter, facebook group and meetup.

We can move faster this way to get the website published.

**Comment by jbelien** [comment]
Do you want to add a new page with Twitter, Facebook, Meetup ?

**Comment by xivk** [comment]
I mean something like this: 

http://jquery-plugins.net/ridiculously-responsive-social-sharing-buttons

Tiny buttons that with just the icons. I would postpone all the event-calendar stuff for after the website launch.

**Comment by jbelien** [comment]
Created http://calendar.osm.akoo.ovh/ : calendar based on Maptime Belgium (and updated automatticaly).
Will create a new page in the website (`develop` branch) to inlcude the calendar.
