### ISSUE TITLE
add project links to wiki

### ISSUE THREAD

**Issue by MarcBessieres** [osmbe/website#22]
add the on going projects we have
add links to their wiki pages like the GRB import

**Comment by joostschouppe** [comment]
done for the Road Completion project

**Comment by jbelien** [comment]
I suppose the wiki page you are talking about is https://wiki.openstreetmap.org/wiki/WikiProject_Belgium

@joostschouppe I remember we struggle to add the Road completion project to the "WikiProject Belgium" green box ; do you remember how you did it ?

**Comment by joostschouppe** [comment]
I think just manually add it here:
https://wiki.openstreetmap.org/w/index.php?title=Template:WikiProject_Belgium&action=edit
