### ISSUE TITLE
add a copyright mention, to a Creative Commons licence I presume

### ISSUE THREAD

**Issue by MarcBessieres** [osmbe/website#24]
I believe we should add a CC licence to our site

I see that the OSM wiki is CC BY SA 2.0
I know there is a version 4.0 but I must admit I don't know the differences

**Comment by jbelien** [comment]
I do not think license is needed on the website.

License is available in the repository : https://github.com/osmbe/website/blob/master/LICENSE.txt

**Comment by xivk** [comment]
- [ ] footer_fr needs some love, translate license line to french!

**Comment by MarcBessieres** [comment]
Done (I hope :)
