### ISSUE TITLE
add a page about how OSM.be is organized and who sponsored

### ISSUE THREAD

**Issue by xivk** [osmbe/website#25]
Add something like this:

http://osm.be/nl/organization

Also update text about OKFN

Basically:

OSM België & OKFN

(logo here)

OpenStreetMap België werkt samen met de Open Knowledge Foundation Belgium (OKFN Belgium). OSM BE werkt als een werkgroep binnen OKFN België. osm.be  osm.be is de verzamelnaam voor alle leden van de OpenStreetMap-gemeenschap in België. De gemeenschap organiseert verschillende activiteiten en ondersteunt elkaar in mapping activiteiten. Door kennis te delen over de OpenStreetMap-wereld verbeteren we onze eigen werking met als einddoel het in kaart brengen van heel België op OpenStreetMap.

(open knowledge logo here)

De Open Knowledge Foundation (OKFN) is een non-profit organisation opgericht in 2004 ter ondersteuning en promotie van open knowledge in al zijn vormen. De Belgische afdeling werd opgericht in februari 2012 om een overkoepelende organisatie te vormen voor open knowledge in België.

OpenStreetMap België ontvangt steun van, of heeft in het verleden steun ontvangen van:

(sponsors here)

**Comment by jbelien** [comment]
I think the footer of the website is enough.

@xivk do you still want to add a specific page about it ?
