### ISSUE TITLE
Rethink "Join" page

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#29]
Now it says: "Join OpenStreetMap Belgium and support us. We will keep you up-to-date on events, news and ongoing projects!"

I think we should clarify here who we would like to "join" (i.e. become member), and what do we expect of them. There should be a much more clear distinction from "signing up for updates".

So I'd suggest something like this:

"
Do you want to join our community? Check out our communication channels (LINK to page explaining meetup, twitter, etc). 

Are you ready to step up your commitment to OpenStreetMap in Belgium? Then become an official member, using the form below. Read more about what it means to be an OSMbe member here (LINK)

Do you just want to be updated about our most important news and activities? Then subscribe to our (infrequent) newsletter with the form below.
"

(EDIT: of course the page about OSMbe membership can only be written AFTER we have the "official" meeting in Brussels)

**Comment by jbelien** [comment]
I totally agree !

Maybe we can now already separate 

- the communication channels (meetup, twitter, mailing list, ...)
- the newsletter subsciption
- the membership 

For the membership page/section, I would only mention the fact it's not "possible" at the moment but we are working on becoming an official chapter.

**Comment by joostschouppe** [comment]
Join ONLY about membership, but automatic subscription to newsletter
Separate page for newsletter subscription only

**Comment by jbelien** [comment]
I think the new registration form closes this issue :)

**Comment by joostschouppe** [comment]
Yep :)

Feel free to merge to main
