### ISSUE TITLE
link mapcomplete.osm.be to mapcomplete.org

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/website#305]
The new domain name is in use. Until the old domain name is fixed, the old website will 404.

**Comment by jbelien** [comment]
`mapcomplete.osm.be` was pointing directly to GitHub.
You'll have to configure the redirect somewhere yourself ; once it's setup somewhere, just give me the IP address (or CNAME) to configure our DNS.

**Comment by jbelien** [comment]
Done: https://github.com/MapComplete/mapcomplete-osm-be
