### ISSUE TITLE
add (google) analytics

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#32]
Or maybe we've already done that?

**Comment by jbelien** [comment]
Not that I know of :)
Do we laready have an Google Analytics account ?
I just need the tracking code (something like UA-********-*)

**Comment by joostschouppe** [comment]
Found it!
UA-38576399-2

**Comment by jbelien** [comment]
Perfect ! I'll take care of that tonight :)

**Comment by jbelien** [comment]
Done !
