### ISSUE TITLE
create url for code of conduct and meeting minutes

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#343]
Create links to the working group bylaws repo, folder minutes and directly to the code of conduct, from osm.be/minutes and osm.be/c_o_c

**Comment by jbelien** [comment]
Implement as redirect to https://github.com/osmbe/working-group-bylaws/ at the moment ; can be improved to proper HTML page.

**Comment by jbelien** [comment]
URL added (also works with `openstreetmap.be`):

Code of conduct:
- https://osm.be/c_o_c
- https://osm.be/c-o-c
- https://osm.be/code-of-conduct
- https://osm.be/en/c_o_c
- https://osm.be/fr/c_o_c
- https://osm.be/nl/c_o_c
- https://osm.be/en/c-o-c
- https://osm.be/fr/c-o-c
- https://osm.be/nl/c-o-c
- https://osm.be/en/code-of-conduct
- https://osm.be/fr/code-of-conduct
- https://osm.be/nl/code-of-conduct

Meeting minutes:
- https://osm.be/minutes
- https://osm.be/en/minutes

Financial report:
- https://osm.be/financial
- https://osm.be/en/financial
