### ISSUE TITLE
Rethink structure to enable pagination

### ISSUE THREAD

**Issue by jbelien** [osmbe/website#37]
Due to actual directory structure (`en`, `nl`, `fr`) it's not possible to enable pagination (and probably other plugins).

What do you think if I change the directory structure the same as I did for the company I work for website ?
See https://github.com/geo6/website and https://geo6.be/

I do not intend to change anything in the resulting website, the pages, the posts, everything stays just as it is right now ; my goal is just to change the structure of the pages so we can enable pagination.

**Comment by xivk** [comment]
This is fine for me... it's clearly an improvement.

**Comment by jbelien** [comment]
Ok, I put that on my to do list 👍

**Comment by jbelien** [comment]
Work in progress in branch `structure`.

**Comment by jbelien** [comment]
You can see the restructured website here : http://147.135.133.184/

**Comment by jbelien** [comment]
New structure is ready but it's not possible to enable pagination (see https://github.com/osmbe/website/issues/16#issuecomment-310479962).

I'm waiting for green light to merge it into `master` :)

**Comment by jbelien** [comment]
**Note for myself :** do not forget to add

```
<script type="text/javascript">
  $( document ).ready(function(){
    var userLang = navigator.language || navigator.userLanguage;
    if (/^nl/.test(userLang) === true) {
      window.location.href = window.location.href + "/nl"
    }
    else if (/^fr/.test(userLang) === true) {
      window.location.href = window.location.href + "/fr"
    }
    else {
      window.location.href = window.location.href + "/en"
    }
  });
</script>
```
