### ISSUE TITLE
add a page about the tasking manager

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#39]
Some inspiration from @jbelien:

The Task Manager is running behind Apache server so it runs on his own now !

The "new" link is http://tasks.osm.be/

Feel free to play around and do not fear to break it ! If it happens, contact me, I'll check what went wrong :D
And feel free to share the link with anyone of course.
You're an administrator so feel free to upgrade user accounts if needed, or delete test projects or anything you want...

When we decide to go to production , it would be nice to redirect something like https://tasks.openstreetmap.be/ to this task manager. Do you know who is in charge of the domain name "openstreetmap.be" ?
(by the way "openstreetmap.brussels" and "openstreetmap.vlaanderen" are still available :P)

I will use the same server to try to host OSM-BE baselayers (one in french, one in dutch - and probably one in german) as soon as I got some rest !

This is currently a small server I rent for 2.99 EUR (without taxes) a month hosted by OVH in France.

We can use this API to show tasks in uMap for instance (or anything similar).
The document is here : https://github.com/hotosm/osm-tasking-manager2/wiki/API

**Comment by jbelien** [comment]
Tasking manager (http://tasks.osm.be) will be decommissioned in a few days.

I'll close this issue (for the moment).
