### ISSUE TITLE
create a page about mapathons

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#41]
Draft:
https://paper.dropbox.com/doc/OSMbe-Mapathon-Support-psvxUqWnvTXC9yi80zOfz

**Comment by jbelien** [comment]
I'll take care of this one in the next few days !

**Comment by jbelien** [comment]
Added in the new version of the website !
Preview : https://jbelien.github.io/osmbe-website/en/project/2017/09/09/project-mapathons.html

**Comment by jbelien** [comment]
Done: https://openstreetmap.be/en/projects/mapathons.html
