### ISSUE TITLE
Directing more people towards the Riot/Matrix channel

### ISSUE THREAD

**Issue by timcouwelier** [osmbe/website#42]
As one of the 'newbies' around, an argument was raised about how it's not overly easy to actually find the Riot channel, where a lot of the core activity is going on / being discussed.

I would like to propose a **direct invitation link to the channel being posted on the front page of osm.be,** and possibly additionally a basic 'how to' on Riot, and detail on why Riot was chosen as an open source alternative to slack / discord which are known to a broader audience.

This would help counter two things:
1) People not being able to find it.
2) People not knowing what the hell this Riot thing is about.

Additionally, this could be extended to a 'sticky' is the Belgium section for the Openstreetmap forums.

**Comment by jbelien** [comment]
Hey @timcouwelier ,

I think that's indeed a good idea to add a link to the Riot channel on osm.be homepage as Riot is now our main way to discuss ! 👍 

I'll take care of that.

**Comment by jbelien** [comment]
Duplicate with #44

**Comment by joostschouppe** [comment]
@timcouwelier l really like the idea of a sticky on the forum. I'm looking into it with Escada. I'd like to put a more general message there about OSM Belgium, obviously with the link to Riot.
