### ISSUE TITLE
Add Riot community page

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#44]
I'd like to add this to the main page, right underneath our community e-mail address.. Is that OK?
 Or better in another place?

Chat channels - https://riot.im/app/#/group/+osmbe:matrix.org

**Comment by jbelien** [comment]
I propose to add a small insert just above the tweets feed with a small text about Riot and the link to https://riot.im/app/#/group/+osmbe:matrix.org

But also a link to https://forum.openstreetmap.org/viewforum.php?id=29 !

**Comment by jbelien** [comment]
I added the insert on the homepage.

Could you list "all" the communications channel we have ? XD

- Riot : https://riot.im/app/#/group/+osmbe:matrix.org
- Forum : https://forum.openstreetmap.org/viewforum.php?id=29
- community@osm.be
- talk-be@openstreetmap.org
- ... ?

**Comment by joostschouppe** [comment]
Twitter!
Facebook: https://www.facebook.com/groups/1419016881706058/
Meetup!

That's it?

**Comment by jbelien** [comment]
Okay, I'll add a page with all those links when I have a bit of time available :)
