### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by jbelien** [osmbe/website#47]
More and more website are switching to HTTPS (mostly thanks to [Let's Encrypt](https://letsencrypt.org/)) and I think it's time for us too :)

**But** it means that we can't use osm.be hosted by GitHub Pages anymore ; unfortunately GitHub Pages does not allow (yet ?) to have our own domain name (osm.be) and HTTPS.

I see (at the moment) 2 solutions :
- Use https://osmbe.github.io/website and redirect http://osm.be to GitHub url ;
- Host ourselves (I can do it) the website (which allow us to have https://osm.be/) ;

I would recommend the second solution ; not very "professional" to have an official website which url is https://***.github.io/*** 😁 
But it would mean that (in a first step) every update has to be manually done on the server hosting https://osm.be/ ; I know it's possible to make to update automatic with tools like Travis or Chef or ... but I have never done it myself and must admit it looks at bit "opaque" at the moment (maybe someone can help me with that 😊 )

**Comment by prmtl** [comment]
Hi!
I'm just passing by, so sorry if I do not know all the details.

I just want to show you all another option. This page can still be hosted on GitHub Pages and have SSL enabled. It is possible if domain will be "delegated" to CloudFlare. In short words, CloudFlare is offering free SSL similar to LetsEncrypt. Here is a guide: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

I have an example page that is set up using CloudFlare SSL and GitHub Pages: https://gh-with-ssl.prmtl.net/ https://github.com/prmtl/gh-with-ssl

**Comment by jbelien** [comment]
@xivk :

Can you update the IP address behind osm.be domain name according to https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider so I can enable HTTPS on osm.be ?

Thanks :)

**Comment by prmtl** [comment]
Great! 🎉 Good to know :D

**Comment by jbelien** [comment]
Still not possible to enable HTTPS and I don't really get why ...

> Not yet available for your site because the certificate has not finished being issued. Please allow 24 hours for this process to complete. (www.osm.be)

**Comment by jbelien** [comment]
I (finally) could enabled the HTTPS here on GitHub pages 🎉
