### ISSUE TITLE
contact page should be outside-oriented, not community oriented

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#49]
The current page http://www.osm.be/contact.html shows ALL the channels. This page should primarly talk to people who are not in the community yet. So it should focus on community@osm.be in th first place. Maybe the other channels need to go somewhere else?

**Comment by jbelien** [comment]
The easiest way (and the way I would choose) is to add a paragraph **before** the `iframe` containing all the channels.

If you have already an idea about the text you would like to see, feel free to post it here or edit the following files :
- https://github.com/osmbe/website/blob/master/contact.html
- https://github.com/osmbe/website/blob/master/contact-fr.html
- https://github.com/osmbe/website/blob/master/contact-nl.html

**Comment by joostschouppe** [comment]
Fixed in the three languages!
The lay out might be improved though
