### ISSUE TITLE
add that we are a local chapter

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#50]
At the footer of the page it currently says: We are a working group and part of Open Knowledge Belgium

That should probably become: We are a working group and part of Open Knowledge Belgium and a Local Chapter (1) of the OpenStreetMap Foundation (2).

link 1: https://wiki.osmfoundation.org/wiki/Local_Chapters
link 2: https://blog.openstreetmap.org/about/

I couldn't find the page where this is defined...

In Dutch: Wij zijn een werkgroep en deel van Open Knowledge Belgium en een Local Chapter van de OpenStreetMap Foundation

**Comment by jbelien** [comment]
Done ! 😃 

The footer information are in the files `footer-*.html` in the directory `_includes`.
