### ISSUE TITLE
Add a donate button

### ISSUE THREAD

**Issue by xivk** [osmbe/website#53]
Can we figure out a quick and simple way to add a donate button to the website?

I'm financing everything personally still and we need a (small) provable source of income to move those services under the Open Knowledge Belgium umbrella.

This doesn't need to be perfect, just simple...

When we have this I can just start donating whatever expenses there are now via the new system and we can move all services to Open Knowledge Belgium (domains and 1 machine).

**Comment by jbelien** [comment]
As you may know, I started working on an app for OpenKnowledge Belgium based on [Stripe](https://stripe.com/be) ; unfortunately, I'm stuck and I think I won't be able to finish it (not enough time).

Here are some solutions that look interesting : 
- PayPal : https://www.paypal.com/be/webapps/mpp/charity
- Stripe Checkout : https://stripe.com/checkout (see [Pricing](https://stripe.com/be/pricing))
- Houdini Project : https://houdiniproject.org/

The last one really seems amazing (and based on Stripe).
It's basically what I had in mind when I was developing my tool. I told Dries I would have a look at it.

Maybe we can start with PayPal Donate button or Stripe Checkout because it's easy to implement and when we have the time move to Houdini (if it fits our needs).

**Comment by jbelien** [comment]
And I think we should keep OpenKnowledge Belgium in this loop because they are looking for something like this as well.

**Comment by xivk** [comment]
Thanks @jbelien cc @Driesvanransbeeck

**Comment by rustyb** [comment]
Hi Folks - I had a crack at making an donation page for the website. Something I've had to do for work recently, and it's really not too hard if we want to keep it super simple for the interm.

Using stripe checkout i've created a page to allow you to choose an amount to donate and then pay by card -> https://github.com/rustyb/website/blob/stripe/donate.html

Choose an amount and click donate:
<img width="921" alt="screen shot 2018-08-04 at 17 45 53" src="https://user-images.githubusercontent.com/53086/43678163-4b825a9c-980e-11e8-88d0-b231aabf9ddc.png">

Fill in the card details:
<img width="377" alt="screen shot 2018-08-04 at 17 46 00" src="https://user-images.githubusercontent.com/53086/43678164-4de74022-980e-11e8-8e44-d28b65918aa4.png">

If you wish to test it out, you will need to clone the repo and serve the jekyll site. For testing stripe handly provides a number of test cards which you can use -> https://stripe.com/docs/testing#cards

## Backend 
For the backend part I created a very simple serverless [webtask](https://webtask.io/make) to allow the actual charging of the card.

All you need to do is head over to webtask.io and sign in. You can create a blank webtask or use the stripe payment processing template already provided in the editor. 

The `/payment` endpoint takes a post request from the stripe checkout form which includes the stripeToken, email address, and the amount to charge.

On a successful payment you will receive a rather nice looking receipt which can be customised in the stripe dashboard - https://stripe.com/docs/receipts

Below is the webtask code. Make sure to setup a secret named `STRIPE_SECRET_KEY` when setting up.
```js
'use latest';

import express from 'express';
import { fromExpress } from 'webtask-tools';
import bodyParser from 'body-parser';
import stripe from 'stripe';

bodyParser.urlencoded();

var app = express();
app.use(bodyParser.urlencoded());

app.post('/payment', (req,res) => {
  var ctx = req.webtaskContext;
  var STRIPE_SECRET_KEY = ctx.secrets.STRIPE_SECRET_KEY;

  stripe(STRIPE_SECRET_KEY).charges.create({
    amount: req.body.amount, // use the amount from the request body
    currency: 'EUR', // set to euro.
    source: req.body.stripeToken, // token from stripe checkout
    description: "Donation to OSM Belgium", // this description will appear on the receipt
    receipt_email: req.body.email
  }, (err, charge) => {
    const status = err ? 400: 200;
    const message = err ? err.message: 'Payment success!';
    res.writeHead(status, { 'Content-Type': 'application/json' });
    return res.end({"message": message});
  });
});

module.exports = fromExpress(app);  

```

**Comment by jbelien** [comment]
That's awesome ! Thanks a lot @rustyb ! 🎉 

I have access to OpenKnowledge Belgium Stripe account, I'll try to set it up and include in our website (for testing at first) in the next days.
I think we can safely say that we won't have more than 1 donation per second, so we can use https://webtask.io ; worst case, I can host it on my server that also hosts https://calendar.osm.be and https://members.osm.be

**Comment by rustyb** [comment]
Good stuff 😄 I'm pretty sure we won't go over the 1 donation per second threshold. @jbelien if you run into any trouble let me know.

@xivk As for dealing with monthly donations this is also possible through stripe's `billing` service. Basically just requires a minor modification to the flow when processing the payment.

**Currently it goes like this:** 
1. user inputs cards details into checkout
2. checkout sends the details to stripe, we get back token representing the card
3. send to the webtask
4. use the token to make the charge
5. Return a successful message to the user.

It might be best to keep both options, so would simply need an additional route on the web task e.g. `subscription`  to handle the slight different flow:

**Subscription flow**
1. user inputs cards details into checkout
2. checkout sends the details to stripe, we get back token representing the card
3. send to the webtask
4. create a customer on stripe using the email and register card token as their default payment method.
5. Create a subscription, with this customer.
6. Return a successful message to the user.

The main drawback to this is that users will need to contact OSM BE to cancel their subscription as stripe does not provide a place for customers to manage their subscriptions out of the box.

Again though this could be easily solved by including a link in the receipt sent out each month that includes the customer_id that we could use cancel a subscription through another route on the webtask.

**Comment by xivk** [comment]
OK, thanks *a lot* @rustyb for helping out and @jbelien for having another go at it, let's start with the regular one-time donations then and move on from there. 
See also here: https://github.com/osmbe/community_planning/issues/3

**Comment by jbelien** [comment]
Okay, I succeeded to make the single donation work : charge the credit card and send the money to OpenStreetMap Stripe sub-account (under OpenKnowledge account).

**but** I always have this error message from my webtask (and so I can't display the success message on my page) : 

```
Code generated an uncaught exception: 
TypeError: First argument must be a string or Buffer 
at ServerResponse.end (_http_outgoing.js:739:13) 
at /data/io/9db2c4d9-0098-4dda-8a6e-f09494ac8734/webtask.js:48:21 
at Timeout._onTimeout (/data/_verquire/stripe/5.4.0/node_modules/stripe/lib/StripeResource.js:94:33) 
at ontimeout (timers.js:498:11) 
at tryOnTimeout (timers.js:323:5) 
at Timer.listOnTimeout (timers.js:290:5)
```

@rustyb Any idea what's wrong in my code :

```
'use latest';

import express from 'express';
import { fromExpress } from 'webtask-tools';
import bodyParser from 'body-parser';
import stripe from 'stripe';

bodyParser.json();

var app = express();
app.use(bodyParser.json());

app.post('/payment', (request, response) => {
  var ctx = request.webtaskContext;
  var STRIPE_SECRET_KEY = ctx.secrets.STRIPE_SECRET_KEY;

  console.log(request.body);

  stripe(STRIPE_SECRET_KEY).charges.create({
    amount: request.body.amount,
    currency: 'eur',
    description: 'Donation to OpenStreetMap Belgium',
    destination: {
      account: ctx.secrets.STRIPE_CONNECT_ACCOUNT,
      amount: request.body.amount
    },
    receipt_email: request.body.email,
    source: request.body.stripeToken
  }, (error, charge) => {
    console.log(error, charge);

    const status = error ? 400 : 200;
    const message = error ? error.message : 'Payment done!';
    response.writeHead(status, { 'Content-Type': 'application/json' });
    return response.end({ 'result': message });
  });
});

module.exports = fromExpress(app);  
```

**Comment by jbelien** [comment]
You can see the result (**work in progress**) here : https://jbelien.github.io/website-osmbe/donate.html

**Comment by jbelien** [comment]
Single donation is working : https://jbelien.github.io/website-osmbe/donate.html

For now, it uses my Stripe account and an OpenStreetMap test sub-account (exactly as it would work under OpenKnowledge account).

You can try with your credit card, it's in **test** mode so your card won't be charged but you can also use [Stripe test cards](https://stripe.com/docs/testing).

**Comment by jbelien** [comment]
Here is the webtask code :
```
'use latest';

import express from 'express';
import { fromExpress } from 'webtask-tools';
import bodyParser from 'body-parser';
import stripe from 'stripe';

bodyParser.json();

var app = express();
app.use(bodyParser.json());

app.post('/payment', (request, response) => {
  var ctx = request.webtaskContext;
  var STRIPE_SECRET_KEY = ctx.secrets.STRIPE_SECRET_KEY;

  stripe(STRIPE_SECRET_KEY).charges.create({
    amount: request.body.amount,
    currency: 'eur',
    description: 'Donation to OpenStreetMap Belgium',
    destination: {
      account: ctx.secrets.STRIPE_CONNECT_ACCOUNT,
      amount: request.body.amount
    },
    receipt_email: request.body.email,
    source: request.body.stripeToken
  }, (error, charge) => {
    if (error) {
      response.writeHead(400, { 'Content-Type': 'application/json' });
      response.write(JSON.stringify({ 'error': error.message }));
    } else {
      response.writeHead(200, { 'Content-Type': 'application/json' });
      response.write(JSON.stringify({ 'success': 'Payment done!' }));
    }
    response.end();
  });
});

module.exports = fromExpress(app);  
```

**Comment by jbelien** [comment]
OpenKnowledge Belgium already has a Stripe account and I have access to it.
I have to create a OpenStreetMap Belgium "sub-account" with [Stripe Connect](https://stripe.com/connect). I'll have a look in the next few days ; just to be sure it's done properly and what kind of information do we need for the sub-account (person in charge, ...).

**Comment by xivk** [comment]
I don't know Stripe very well? I guess a sub-account means we can have an overview of what we receive and from who easily and that this is separate from the rest of the 'accounts'? 

I guess you can add my personal info or perhaps @Driesvanransbeeck knows more about this...

**Comment by xivk** [comment]
Let's finish this off, and come up with a piece of text to put on top?

- [ ] English text about donations.
- [ ] Dutch text about donations.
- [ ] French text about donations.

Do we put a button on the frontpage?

**Comment by xivk** [comment]
English:

> Donating to OSM Belgium helps our group to host this website, refund travel expenses for volunteers, and it enables us to organize specific projects. We also use the donations to have t-shirts, stickers and banners made for promotion.

**Comment by jbelien** [comment]
> Do we put a button on the frontpage ?

We can do that of course ;
And by default, there will be a "Donate" in the main menu (we can choose the order but I would put it last so it's more visible)

**Comment by xivk** [comment]
I'm not sure about the donate menu... we already have a bunch of menu items (Home, News, Join, Projects, Calendar, Contact). Perhaps a donate button that links to /donate without a direct menu item?

**Comment by jbelien** [comment]
I can do that too, no problem 😄 

We have to think where to put that donate button on the homepage then ...
It has to be as visible as possible but not aggressive.

**Comment by xivk** [comment]
Below have a question and above the tweets:

![image](https://user-images.githubusercontent.com/1128068/44204355-1bbfb300-a14a-11e8-833f-b50b8f5c30a8.png)

**Comment by xivk** [comment]
That's what I was thinking :-)

**Comment by jbelien** [comment]
Seems good to me 👍 

I'll try to move further on this ASAP 😃
