### ISSUE TITLE
Template page for using OSM-be tiles in a leaflet / openlayers map applet

### ISSUE THREAD

**Issue by timcouwelier** [osmbe/website#67]
As suggested by Jakka in the Riot Channel:

We could use a code template, easily found on website, on how people can use the OSM-be tiles in a webmap (with attribution and all), with a demo on how to use a marker in the map.

A demo page + a code snippet where we mark what needs to be changed in order to make the code work for integration in a website (and possibly bundel all those variables in one block at the start?)

**Comment by jbelien** [comment]
There is already:
- https://github.com/jbelien/openstreetmap-carto-be/wiki/OpenLayers
- https://github.com/jbelien/openstreetmap-carto-be/wiki/Leaflet
but I'll improve it !

**Comment by timcouwelier** [comment]
I'd like to see a demo for a marker (+ text upon clicking the marker) included, as that's the key feature people would use it for?

**Comment by jbelien** [comment]
Hello @timcouwelier 

I added a "HowTo" page on the website : https://openstreetmap.be/en/projects/howto.html
Feedback is welcome !
