### ISSUE TITLE
Add a link to a map

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/website#71]
We should probably add a link on the frontpage for people who want to see some maps!

**Comment by jbelien** [comment]
That's a good idea !

Only a link to https://openstreetmap.org/ ?
Or also a link to https://tile.openstreetmap.be/ ?
Something else ?

**Comment by jbelien** [comment]
I created a "HowTo" page : https://openstreetmap.be/en/projects/howto.html

I added a "How to see the map" :P
