### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by mart-e** [osmbe/website#85]
Hello,

I would like to subscribe to the list of events on https://openstreetmap.be/en/news.html
but it looks like there is no RSS feed.
Could you add one please?

Thanks

**Comment by jbelien** [comment]
Hello @mart-e , here is the URL of the feed : https://openstreetmap.be/feed.xml

**Comment by jbelien** [comment]
Hello @mart-e,

There is a feed available here: https://openstreetmap.be/feed.xml
But I just noticed the posts and events are indeed not in the feed ... Strange, I'll have a look ASAP !

**Comment by mart-e** [comment]
Thanks!
Is this URL present in the interface? I did not found it on the main pages.

**Comment by jbelien** [comment]
>  Is this URL present in the interface? I did not found it on the main pages.

Probably not 🙄

**Comment by jbelien** [comment]
I think I found the "issue".

It seems that the `jekyll-feed` plugin doesn't like my structure for the posts.
The main issue is that we have 3 languages and that Jekyll isn't built for such use case. There are some plugins that do the trick but they are [not supported by GitHub pages](https://pages.github.com/versions/).

So I don't have a solution at the moment but I'm definitely open to suggestions...

**Comment by mart-e** [comment]
I don't know jekyll but as I understand it, the posts in the feed are generated from
https://github.com/osmbe/website/blob/860900d3e73ea617419beb6d8513f50cccfef89e/feed.json#L21

and the problem is that `site.posts` does not contains the events, right?
Or do you wish to create one different feed per language?

**Comment by jbelien** [comment]
You're right !
**But** you're talking here about the [**JSON** feed](https://openstreetmap.be/feed.json) and not the [**RSS** feed](https://openstreetmap.be/feed.xml).
My comments are related to the RSS feed (generated by the `jekyll-feed` plugin).

The JSON feed is indeed much more flexible since I generate it myself.

**Comment by mart-e** [comment]
It seems that `jekyll-feed` supports generating feed for custom collections
https://github.com/jekyll/jekyll-feed#collections

Wouldn't adding
```
feed:
  collections:
    - events
```
do the trick and, if I understand correctly, create a `feed/events.xml` feed?

I also found [this article](http://stories.upthebuzzard.com/jekyll_notes/2017-02-19-rss-feed-for-all-jekyll-collections.html) explaining how to generate a feed combining multiple sources but it is creating a feed fully manually (which is a bit sad while `jekyll-feed` already does almost what you want).

**Comment by jbelien** [comment]
Interesting !
I'll give it a try 👍

**Comment by jbelien** [comment]
Dear @mart-e you're totally right!

RSS feed for the posts is https://openstreetmap.be/feed.xml
RSS feed for the events is https://openstreetmap.be/feed/events.xml

Thank you! 🍾

**Comment by mart-e** [comment]
Great, thanks for the update !
